// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// EM
arma::rowvec EM(int n1, int n2, int num_snp, int num_per, arma::mat sigma, double alpha, double sigma_beta, double sigma_gamma, arma::colvec ldscore, arma::mat zscore);
RcppExport SEXP _OMR_EM(SEXP n1SEXP, SEXP n2SEXP, SEXP num_snpSEXP, SEXP num_perSEXP, SEXP sigmaSEXP, SEXP alphaSEXP, SEXP sigma_betaSEXP, SEXP sigma_gammaSEXP, SEXP ldscoreSEXP, SEXP zscoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type num_snp(num_snpSEXP);
    Rcpp::traits::input_parameter< int >::type num_per(num_perSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_gamma(sigma_gammaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ldscore(ldscoreSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zscore(zscoreSEXP);
    rcpp_result_gen = Rcpp::wrap(EM(n1, n2, num_snp, num_per, sigma, alpha, sigma_beta, sigma_gamma, ldscore, zscore));
    return rcpp_result_gen;
END_RCPP
}
// NR
arma::colvec NR(int n1, int n2, int num_snp, int num_per, arma::mat sigma, double alpha, double sigma_beta, double sigma_gamma, arma::colvec ldscore, arma::mat zscore);
RcppExport SEXP _OMR_NR(SEXP n1SEXP, SEXP n2SEXP, SEXP num_snpSEXP, SEXP num_perSEXP, SEXP sigmaSEXP, SEXP alphaSEXP, SEXP sigma_betaSEXP, SEXP sigma_gammaSEXP, SEXP ldscoreSEXP, SEXP zscoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type num_snp(num_snpSEXP);
    Rcpp::traits::input_parameter< int >::type num_per(num_perSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_beta(sigma_betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma_gamma(sigma_gammaSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type ldscore(ldscoreSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zscore(zscoreSEXP);
    rcpp_result_gen = Rcpp::wrap(NR(n1, n2, num_snp, num_per, sigma, alpha, sigma_beta, sigma_gamma, ldscore, zscore));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_hello_world
arma::mat rcpparma_hello_world();
RcppExport SEXP _OMR_rcpparma_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpparma_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_outerproduct
arma::mat rcpparma_outerproduct(const arma::colvec& x);
RcppExport SEXP _OMR_rcpparma_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_innerproduct
double rcpparma_innerproduct(const arma::colvec& x);
RcppExport SEXP _OMR_rcpparma_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpparma_bothproducts
Rcpp::List rcpparma_bothproducts(const arma::colvec& x);
RcppExport SEXP _OMR_rcpparma_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpparma_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}
