# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' @export
EM <- function(n1, n2, num_snp, num_per, sigma, alpha, sigma_beta, sigma_gamma, ldscore, zscore) {
    .Call(`_OMR_EM`, n1, n2, num_snp, num_per, sigma, alpha, sigma_beta, sigma_gamma, ldscore, zscore)
}
#' @export
NR <- function(n1, n2, num_snp, num_per, sigma, alpha, sigma_beta, sigma_gamma, ldscore, zscore) {
    .Call(`_OMR_NR`, n1, n2, num_snp, num_per, sigma, alpha, sigma_beta, sigma_gamma, ldscore, zscore)
}

rcpparma_hello_world <- function() {
    .Call(`_OMR_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_OMR_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_OMR_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_OMR_rcpparma_bothproducts`, x)
}

